printf "\033c"
echo ""
echo ""
echo "		    ======================================"
echo "		    |           Average Pianist          |"
echo "		    |                2016                |"
echo "		    ======================================"
echo "		    |                                    |"
echo "		    |  Cantina band with floppy drives.  |"
echo "		    |  You can't get better than this.   |"
echo "		    |                                    |"
echo "		    ======================================"
echo ""
echo ""
echo ""
read -n1 -r -p "		   Press enter to travel far, far away... "
echo ""
echo ""
echo ""
echo ""
echo ""
python ~/Raspi_GPIO/florchestra/python/flusicengine_duo.py cantina